package Verein;

/**
* Verein/VereinsmitgliedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

public final class VereinsmitgliedHolder implements org.omg.CORBA.portable.Streamable
{
  public Verein.Vereinsmitglied value = null;

  public VereinsmitgliedHolder ()
  {
  }

  public VereinsmitgliedHolder (Verein.Vereinsmitglied initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Verein.VereinsmitgliedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Verein.VereinsmitgliedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Verein.VereinsmitgliedHelper.type ();
  }

}
