package Verein;


/**
* Verein/VereinsmitgliedHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

abstract public class VereinsmitgliedHelper
{
  private static String  _id = "IDL:Verein/Vereinsmitglied:1.0";

  public static void insert (org.omg.CORBA.Any a, Verein.Vereinsmitglied that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Verein.Vereinsmitglied extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Verein.VereinsmitgliedHelper.id (), "Vereinsmitglied");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Verein.Vereinsmitglied read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VereinsmitgliedStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Verein.Vereinsmitglied value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Verein.Vereinsmitglied narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Verein.Vereinsmitglied)
      return (Verein.Vereinsmitglied)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Verein._VereinsmitgliedStub stub = new Verein._VereinsmitgliedStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Verein.Vereinsmitglied unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Verein.Vereinsmitglied)
      return (Verein.Vereinsmitglied)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Verein._VereinsmitgliedStub stub = new Verein._VereinsmitgliedStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
