package Verein.VereinsmitgliedPackage;

/**
* Verein/VereinsmitgliedPackage/vereinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

public final class vereinHolder implements org.omg.CORBA.portable.Streamable
{
  public Verein.VereinsmitgliedPackage.verein value = null;

  public vereinHolder ()
  {
  }

  public vereinHolder (Verein.VereinsmitgliedPackage.verein initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Verein.VereinsmitgliedPackage.vereinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Verein.VereinsmitgliedPackage.vereinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Verein.VereinsmitgliedPackage.vereinHelper.type ();
  }

}
