package Verein.VereinsmitgliedPackage;


/**
* Verein/VereinsmitgliedPackage/VereinSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

abstract public class VereinSeqHelper
{
  private static String  _id = "IDL:Verein/Vereinsmitglied/VereinSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, Verein.VereinsmitgliedPackage.verein[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Verein.VereinsmitgliedPackage.verein[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Verein.VereinsmitgliedPackage.vereinHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Verein.VereinsmitgliedPackage.VereinSeqHelper.id (), "VereinSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Verein.VereinsmitgliedPackage.verein[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Verein.VereinsmitgliedPackage.verein value[] = null;
    int _len0 = istream.read_long ();
    value = new Verein.VereinsmitgliedPackage.verein[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Verein.VereinsmitgliedPackage.vereinHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Verein.VereinsmitgliedPackage.verein[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Verein.VereinsmitgliedPackage.vereinHelper.write (ostream, value[_i0]);
  }

}
