package Verein.VereinsmitgliedPackage;


/**
* Verein/VereinsmitgliedPackage/VereinSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

public final class VereinSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Verein.VereinsmitgliedPackage.verein value[] = null;

  public VereinSeqHolder ()
  {
  }

  public VereinSeqHolder (Verein.VereinsmitgliedPackage.verein[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Verein.VereinsmitgliedPackage.VereinSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Verein.VereinsmitgliedPackage.VereinSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Verein.VereinsmitgliedPackage.VereinSeqHelper.type ();
  }

}
