package Verein.VereinsmitgliedPackage;


/**
* Verein/VereinsmitgliedPackage/verein.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verein.idl
* Montag, 25. Juni 2018 11:14 Uhr MESZ
*/

public final class verein implements org.omg.CORBA.portable.IDLEntity
{
  public String vname = null;
  public short vbeitrag = (short)0;
  public Verein.Type vtype = null;
  public String city = null;

  public verein ()
  {
  } // ctor

  public verein (String _vname, short _vbeitrag, Verein.Type _vtype, String _city)
  {
    vname = _vname;
    vbeitrag = _vbeitrag;
    vtype = _vtype;
    city = _city;
  } // ctor

} // class verein
